services:
  - type: web
    name: cni-cyber-backend
    env: python
    region: singapore
    buildCommand: "cd backend && pip install -r requirements.txt && pip install bcrypt"
    startCommand: "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cni-postgres-db
          property: connectionString

databases:
  - name: cni-postgres-db
    databaseName: cni_cyber_db
    user: cni_admin
    region: singapore
